### ISSUE TITLE
[Bug]: One Extra Waystone Generating per Village

### ISSUE THREAD

**Issue by JacobTDC** [LordDeatHunter/FabricWaystones#280]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

https://github.com/LordDeatHunter/FabricWaystones/pull/277 mostly solved an issue with extra waystones generating in CTOV villages when Lithostitched is installed, however, now it seems that Wraith Waystones always generates one more waystone per CTOV village than is set in the config.

Using the latest versions of CTOV (3.4.12), Wraith Waystones (3.3.3), Lithostitched (1.4.4), and owo-lib (0.11.2) for Minecraft Fabric 1.20.1 at time of writing.

### To Reproduce

Install all relevant mods with default configs, create a superflat world, and run `/place structure ctov:medium/village_taiga` (or any other CTOV village).

### Expected behavior

By default, only a single waystone should generate per village, or however many are set in the config.

### Mod Version

v3.3.3

### Minecraft Version

1.20.1

### Java Version

Java 17

### Fabric Version

- **Fabric:** 0.16.10+1.20.1
- **Fabric API:** 0.92.3+1.20.1

### Relevant log output

```shell

```

**Comment by Apollounknowndev** [comment]
CTOV issue. Both Fabric Waystones *and* CTOV add waystones to CTOV villages, so CTOV just needs to remove their injection.

**Comment by JacobTDC** [comment]
> CTOV issue. Both Fabric Waystones *and* CTOV add waystones to CTOV villages, so CTOV just needs to remove their injection.

I just have absolutely no luck when it comes to identifying the correct place to open an issue...

**Comment by Apollounknowndev** [comment]
Don't worry about it, this issue is invisible without actually looking at the code :P

**Comment by ChoiceTheorem** [comment]
So, I will remove my injection for waystones.

**Comment by WxAaRoNxW** [comment]
question, is the injection the one in fwaystone's config file? or on ctov's side

**Comment by ChoiceTheorem** [comment]
> question, is the injection the one in fwaystone's config file? or on ctov's side

I'll remove the one in CTOV side. The one in fwaystone config will be retained.

**Comment by LordDeatHunter** [comment]
@ChoiceTheorem not sure if that's required after #276 & #277

**Comment by WxAaRoNxW** [comment]
> [@ChoiceTheorem](https://github.com/ChoiceTheorem) not sure if that's required after [#277](https://github.com/LordDeatHunter/FabricWaystones/pull/277) & [#279](https://github.com/LordDeatHunter/FabricWaystones/pull/279)

but op says that they're on v3.3.3, which is the lithostitched compat no?

**Comment by Onewingseraphim** [comment]
Anyone know why this is happening to me lol, there's like 20 in one village

![Image](https://github.com/user-attachments/assets/cb8b4171-17de-432e-8fbf-375c4d972dbe)

**Comment by ChoiceTheorem** [comment]
This bug is fixed for 1.20.1 but not 1.21

**Comment by Nova-Katt** [comment]
> This bug is fixed for 1.20.1 but not 1.21

Several months later. Is there a way for us to manually fix this from the config file or something?
I'm running 1.21.1 and my villages have anything from 5 to 20 waypoints aswell. ^^;

Could it also be other village mods that interfere? I am running quite a bunch of stuff.
CTOV 3.5.10a
Lithostiched 1.5.0
Better Village 3.3.1
MoreVillagers 5.2.0 + Missing Buildings 1.0.0

I also have a bunch of structure addons, most which doesn't modify villages, like YUNG's mineshafts and the like, but some of them I don't know if they add anything specifically to villages, so I'll list them just in case.
Additional Structures 5.1.0
Dungeons and Taverns 4.4.4
Medieval Buildings 1.1.1
Moogs Voyager Structures 5.0.1
SparseStructures 3.0 (shouldn't do anything since it should just make stuff more rare, but again, will list just in case)

**Note:** I haven't started playing on this modpack yet. It's currently in the process of picking mods and starting the game up piece  by piece to see what works. So if something is a buggy mess it's easy for me to just yeet it for now if that's needed. :)

**Comment by Nova-Katt** [comment]
Actually, an update to that. After removing CTOV I still have the same issue, and after then looking at Better Villages, someone reported the same issue on NeoForge, so my guess is that there is a compatibility issue between Wraith Waystones and Better Villages.
I reported it on Better Villages as well!

UPDATE: Ignore that.... when I used only CTOV and Wraith Waystones i found a large ctov village with 17 waystones..
So...
maybe the issue is with Wraith Waystones then, since it doesn't matter if I run CTOV or Better Villages.

**Comment by NovaLynxie** [comment]
Is this still being looked into? (sorry if am bumping an old issue ticket, will make a new one if necessary)
Been seeing this happen repeatedly in newly generated villages in Fabric 1.21.1. Seen some commits that was supposed to address this in #279 but that looks like it hasn't worked and was nearly a year ago.
I have been using CTOV for my villages and seeing more than one waystone spawned, even placing themselves in weird places.
May just have to completely disable them generating in villages if that is still broken since I'd rather not pull it from my worlds :/

**Comment by LordDeatHunter** [comment]
This has been fixed from 1.21.4 onwards. I haven't made a backport fix yet.
